version: '3.1'

services:
  db:
    image: mariadb:10.5
    volumes:
     - ./mariadbconfig:/etc/mysql/mariadb.conf.d
     - ./mysql:/var/lib/mysql 
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
  wordpress: 
    container_name: wordpress_mariadb
    depends_on: 
      - db
    environment: 
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: p@ssw0rd
      WORDPRESS_DB_USER: root
    image: "wordpress:latest"
    ports: 
      - "8005:80"
    restart: always
    volumes: 
      - "./wordpress:/var/www/html"
volumes: 
  mysql: {}